### ISSUE TITLE
Vegetation Rule

### ISSUE THREAD

**Issue by RebeccaHager** [Unit26Y21/UrbanLab#12]
@htarrido-cuny
I added now vegetation into the code and it is sending me errors. I think it might be because I added it separately at the bottom instead of just adding it into the list of vegetation that was already in the code but I wanted it to be separate because it is a different type of vegetation.
And I dont fully understand the function of the code so I'm not sure how I would place things on the site
[211121 VegetationCatalog.txt](https://github.com/Unit26Y21/UrbanLab/files/7615035/211121.VegetationCatalog.txt)

**Comment by htarrido-cuny** [comment]
This was address during class.

**Comment by htarrido-cuny** [comment]
its on main-ecology now.
