### ISSUE TITLE
Waste_DensitybyBldClass Rule

### ISSUE THREAD

**Issue by kkenny000** [Unit26Y21/UrbanLab#2]
Questions on rule: 
- Should we add in an attribute that adds sqft to each household? 
- Attempted to assign a color to each different building type, but it not displaying when I generate the rule 

- I'm getting a mismatch error (expecting float, got string) for the below... not sure how to adjust? 
report("Lbs of Organics", averageBuildingWaste("Organics", NumberofHouseholds))

**Comment by htarrido-cuny** [comment]
Attempted to assign a color to each different building type, but it not displaying when I generate the rule. This is solved with the current commit

**Comment by htarrido-cuny** [comment]
> I'm getting a mismatch error (expecting float, got string) for the below... not sure how to adjust?
> report("Lbs of Organics", averageBuildingWaste("Organics", NumberofHouseholds))

This as well
