### ISSUE TITLE
TheEquation_BalanceSpaces

### ISSUE THREAD

**Issue by anaace1** [Unit26Y21/UrbanLab#4]
@htarrido-cuny 
We determined a formula for knowing the area of Balance Spaces per Block:

BlockPopulation=BlockArea/DensityPerBlock
StreetArea=ST_Width*ST_Length
RequiredArea=BlockPopulation*EventDesity

"BalanceSpaceArea=RequiredArea-StreetArea"

EventDensity is a constant (6 sqft/person)
DensityPerBlock is a constant (6.5 inh/block)
We established BlockArea as a constant for now (120.000 sqft)

Doubts:
How can I select the Streets that surround a Block in order to determine BlockArea?
How to select the Street that is close to the block, in order to determine the StreetArea?

Also, probably there are mistakes in the code.

`/**
 * File:    TheEquation.cga
 * Created: 11 Nov 2021 21:33:26 GMT
 * Author:  mozar
 */

version "2019.0"
#####Constants#####

const BlockArea= (120000)
const DensityPerBlock= (6.5)
const EventDensity= (6)

#####Functions#####
BlockPopulation(BlockArea, DensityPerBlock)=
	BlockArea/DensityPerBlock
	
RequiredArea(BlockPopulation, EventDensity) =
	BlockPopulation*EventDensity
	
StreetArea(ST_WIDTH, SHAPE_Leng)=
	ST_WIDTH*SHAPE_Leng
	
BalanceSpaceArea(RequiredArea, StreetArea)=
	RequiredArea-StreetArea

#####Rules#####
@StartRule
BalanceSpace-->
	#splitArea()
	color ("#edffc2")`

**Comment by htarrido-cuny** [comment]
pushed some changes to improve the codes readability and execution
