### ISSUE TITLE
Scatter in primitive quad?

### ISSUE THREAD

**Issue by anaace1** [Unit26Y21/UrbanLab#6]
Hello @htarrido-cuny 
We are trying to insert assets in the areas defined below in the code. However, regarding the TablesChairsScatter and TablesChairsArea, it is only inserting one OutdoorFurniture.dae in the primitiveQuad. We want to scatter 10 OutdoorFurtinture.dae in the 6x6 area defined in the primitiveQuad.

`SplitSpace-->
	split(u, unitSpace, 0){ 6 : TablesChairsArea 
							| 10 : Playground
							| 5 : NIL
							| 6 : AmebaBench 
							| 6 : TablesChairsArea 
							| 2 : MediaTotem
							| 9 : LightPlaza
							|10 : NIL 
							| 6 : AmebaBench 
							| 6 : TablesChairsArea
							| 10 : Playground
							| 6 : AmebaBench 
							| 6 : TablesChairsArea
							|10 : NIL }*			
							  	

TablesChairsScatter-->
	scatter(surface, 10, uniform) { TablesChairsArea }
								
TablesChairsArea-->
	primitiveQuad(6,6)
//	i("OutdoorFurniture.dae", yUp, keepSizeAlignPosition)
	
Playground-->
	primitiveQuad(8,8)
	color("#e88279")
	
MediaTotem-->
	primitiveCube(0.4, 2, 0.4)
		
LightPlaza-->
	primitiveQuad(9,9)
	color("#757575")		
	
AmebaBench-->
	primitiveQuad(6,4)
	color("#e6fcc0")`

**Comment by htarrido-cuny** [comment]
Check my comments on your branch
