### ISSUE TITLE
EventLanes Rules problems

### ISSUE THREAD

**Issue by anaace1** [Unit26Y21/UrbanLab#7]
Hello again @htarrido-cuny!

Here we are defining areas for our events. We are starting dividing the Block (without subdivisions), however, sometimes is difficult to determine the value in the offset, is it possible to adapt the offset to the size of the block, like interpolating? Perhaps it has something to do with the centroid of the polygon, don't know exactly. Also, we tried to insert some Kiosks in the second ring with no success.

`@StartRule

BlockDivision-->
	offset(-3)OffsetSelector
//	split(x){ { 2 : A | 3 : B }* }
 	
 OffsetSelector-->
	comp(f){ inside: Second | border: First } 
 
First-->
	color ("#ffcf54")
 
Second-->
	color ("#e88079")
	offset(-3)OffsetSelector2
	split(x){ { 2 : Kiosks | 3 : NIL }* }
	
Kiosks -->
	primitiveQuad(2,3)
	i("Street Vendor.dae", yUp, keepSizeAlignPosition)
     
OffsetSelector2-->
	comp(f) { inside: Third | border: Second } 
	
Third-->
	color("#c8f5a2")`

**Comment by htarrido-cuny** [comment]
Can you provide a sketch or drawing showing what you expect to happen?

**Comment by anaace1** [comment]
![IMG_8076](https://user-images.githubusercontent.com/92740297/142896214-1edb5a96-98a2-4ac4-913e-b939bf3515da.jpg)

Yes, this a very quick sketch of the idea

**Comment by htarrido-cuny** [comment]
this can be done in city engine. yes...

**Comment by htarrido-cuny** [comment]
pushed example of how one might about it
